### ISSUE TITLE
Getting unexpected < error when trying JSX in component 

### ISSUE THREAD

**Issue by scdba** [adrianmcli/nano-react-app#34]
Trivial JSX functional component

import React from "react"
const Thing = () => {
    return (<p>Hope</p>)
}
export default Thing

gives me 

❯ npm start

> deleteme@0.1.0 start
> vite

 > src/components/Thing.js:2:12: error: Unexpected "<"
    2 │     return (<p>Hope</p>)
      ╵             ^

error when starting dev server:
Error: Build failed with 1 error:
src/components/Thing.js:2:12: error: Unexpected "<"
    at failureErrorWithLog (/Users/aryagunawatsonsc/ag-learn/deleteme/node_modules/esbuild/lib/main.js:1493:15)
    at /Users/aryagunawatsonsc/ag-learn/deleteme/node_modules/esbuild/lib/main.js:1151:28
    at runOnEndCallbacks (/Users/aryagunawatsonsc/ag-learn/deleteme/node_modules/esbuild/lib/main.js:941:63)
    at buildResponseToResult (/Users/aryagunawatsonsc/ag-learn/deleteme/node_modules/esbuild/lib/main.js:1149:7)
    at /Users/aryagunawatsonsc/ag-learn/deleteme/node_modules/esbuild/lib/main.js:1258:14
    at /Users/aryagunawatsonsc/ag-learn/deleteme/node_modules/esbuild/lib/main.js:629:9
    at handleIncomingPacket (/Users/aryagunawatsonsc/ag-learn/deleteme/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/Users/aryagunawatsonsc/ag-learn/deleteme/node_modules/esbuild/lib/main.js:596:7)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:312:12)=========
whereas 
    return ("<p>Hope</p>")
is OK
(except it's useless !)

=========
App.jsx:

import React from "react";
import Thing from "./components/Thing"

export default () => (
  <>
    <h1>Welcome to React Vite Micro App!</h1>
    <p>Hard to get more minimal than this React app.</p>
    <Thing />
  </>
);

Any ideas ?
Sorry if it is blindingly obvious !

**Comment by scdba** [comment]
Ah - so they have to be _.jsx_ files !!
